### ISSUE TITLE
Kind request to hide package from Atmosphere

### ISSUE THREAD

**Issue by dandv** [hpx7/meteor-accounts-ui-bootstrap-3#1]
Hey @hpx7,

While looking for accounts-ui packages for Bootstrap 3 on Atmosphere I found [yours](https://atmospherejs.com/hpx7/accounts-ui-bootstrap-3). It looks like you haven't had time to maintain it, which is perfectly ok.

In the meantime though, much more actively maintained packages have appeared, such as @ianmartorell's https://atmospherejs.com/ian/accounts-ui-bootstrap-3.

To keep Atmosphere clean, we kindly ask you to hide the old package. No worries, it will still be installable by apps and dependent packages; it will just be hidden from Atmosphere searches:

```
meteor admin set-unmigrated hpx7:accounts-ui-bootstrap-3
```

Thanks,
Dan
Atmosphere curator

**Comment by hpx7** [comment]
Done!
